### ISSUE TITLE
Seems to be missing the music files

### ISSUE THREAD

**Issue by lmamane** [qirien/personal-space2#2]
Running it gives (after the developer name interstitial) error:

IOError: Couldn't find file 'music/12-Found-Jeff Wahl_.ogg'

**Comment by qirien** [comment]
Yes, these music files are copyrighted and while we have a license to include them with the commercial version of the game, I did not put them on GitHub.
If you ignore the error, you should be able to continue but without music.
Or, you can buy the full game here:
https://www.metasepiagames.com/SpaceToGrow/index.html

Apr 5, 2022 12:29:39 lmamane ***@***.***>:
