### ISSUE TITLE
family 28 unreachable code total_faction vs faction

### ISSUE THREAD

**Issue by lmamane** [qirien/personal-space2#3]
```
                    "I decided to ask around. Maybe someone else had seen her."
                    if (mavericks > 10):
                    (...)
                    if (miners > 10):
                    (...)
                    if (colonists > 10):
                    (...)
```

It is basically impossible for in-year increase of faction to exceed 10. You probably meant total_mavericks, total_miners and total_colonists? (Just calling ${faction}_strong at year 28 would require at least 10, not strictly more than 10.)

**Comment by qirien** [comment]
Good catch! Looks like I forgot to change that when we changed how we used those variables
It should be fixed on github and will be in the next release. Thanks for reporting!
